### ISSUE TITLE
Stops tracking unread comments once a thread exceeds ~300 comments

### ISSUE THREAD

**Issue by danhermann** [etcet/HNES#148]
Some time in the last couple of weeks, it's stopped tracking unread comments in threads once they reach a certain number of comments ~300. For example, new comment tracking was working fine up to ~170 comments in the thread below, but after a refresh in which the comment count hit 393, there were no more unread comment indicators. Observed consistently in any thread with more than ~300 comments.

https://news.ycombinator.com/item?id=15591441

Chrome Version 61.0.3163.100 (Official Build) (64-bit) on Win10

**Comment by etcet** [comment]
I've fixed some new comment highlighting bugs in https://github.com/etcet/HNES/commit/81bc768e8f53e2cf2e8946a9a3f3594b0c984395. But I can't confirm it fixes this reported issue, so I'll leave this open and please let me know if it occurs again.

**Comment by danhermann** [comment]
@etcet, thank you for looking into it. I do still see the issue with the 1.5.0.1 version of the plugin. FWIW, it seems to coincide with another issue I've noticed on threads with lots of comments and that is a right-justified repeat of the thread header interleaved with the comments (whether or not the comment threads are collapsed). E.g.:
![image](https://user-images.githubusercontent.com/22777892/33038261-a9c37936-cdf9-11e7-814d-cb40a7e4bc29.png)

**Comment by danhermann** [comment]
Fwiw, I'm no longer seeing this behavior though I'm not sure if it's due to changes in 1.5.0.2 or something else.

**Comment by danhermann** [comment]
Closing this as this problem appears to be fixed in recent releases.
